language: cpp
jobs:
  include:
    # osx
    - os: osx
      env: BUILD_TARGET=osx
      osx_image: xcode11.6
    # ios
    - os: osx
      env: BUILD_TARGET=ios
      osx_image: xcode11.6
    # android
    - os: linux
      dist: xenial
      env: 
        - BUILD_TARGET=android
        - PYENV_VERSION=2.7.13
      language: android
    # linux
    - os: linux
      dist: bionic
      env: 
        - BUILD_TARGET=linux 
        - GEN_BINDING_AND_COCOSFILE=false
    # android_lua
    #- os: linux
    #  env: BUILD_TARGET=android_lua
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #      packages:
    #        - g++-6
    #- os: linux
    #  env: BUILD_TARGET=android_cocos_new_test
    #- os: linux
    #  env: BUILD_TARGET=linux_cocos_new_test
    #- os: osx
    #  env: BUILD_TARGET=ios_cocos_new_lua_test
    #  osx_image: xcode11
    #- os: osx
    #  env: BUILD_TARGET=ios_cocos_new_cpp_test
    #  osx_image: xcode11

script:
  - while sleep 9m; do echo "=====[ Build is still running after $SECONDS seconds ]====="; done &
  - tools/travis-scripts/run-script.sh
  - kill %1
before_install:
  - tools/travis-scripts/before-install.sh

jdk:
  - oraclejdk8

cache:
  bundler: true

notifications:
  email: false

# blocklist
branches:
  except:
  - v4
