name: pull_request

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PULL_REQUEST: yes

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.8'
      - uses: ilammy/msvc-dev-cmd@v1.12.1
        with: 
          arch: ${{ env.BUILD_ARCH }}
      - name: Build
        shell: pwsh
        run: .\build.ps1 -p win32 -a x64

  build-winuwp:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.8'
      - uses: ilammy/msvc-dev-cmd@v1.12.1
        with: 
          arch: x64
          uwp: true
      - name: Build
        shell: pwsh
        run: .\build.ps1 -p winuwp -a x64

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install deps
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
        run: |
          AX_ROOT=`pwd`
          echo -e "y" | pwsh $AX_ROOT/setup.ps1
      - name: Build
        shell: pwsh
        run: ./build.ps1 -p linux -a x64

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        shell: pwsh
        run: |
          $AX_ROOT = $(Get-Location).Path
          ./build.ps1 -p android -a arm64

  build-osx:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build
        shell: pwsh
        run: ./build.ps1 -p osx -a x64

  build-ios:
    name: build-ios
    runs-on: macos-latest
    env:
      GH_OS_NAME: osx
      BUILD_TARGET: ios
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build
        shell: pwsh
        run: ./build.ps1 -p ios -a x64

  build-tvos:
    name: build-tvos
    runs-on: macos-latest
    env:
      GH_OS_NAME: osx
      BUILD_TARGET: tvos
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build
        shell: pwsh
        run: ./build.ps1 -p tvos -a x64
