name: site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - dev
    paths:
      - core/**/*
      - docs/**/*
      - .github/workflows/site.yml
      - tools/ci/build-site.ps1
  workflow_dispatch:
    
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Build HTML site
      shell: pwsh
      run: |
        $env:AX_DOCS_TOKEN = '${{ secrets.AX_BOT_TOKEN }}'
        ./tools/ci/build-site.ps1
    
    # Deploy HTML site to GitHub Pages
    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/dist/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages
